"""baseline schema

Revision ID: 1ed686273e87
Revises: 
Create Date: 2026-05-24 21:13:31.740365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ed686273e87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PLAYER', 'ORGANIZER', 'ADMIN', 'SUPER_ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('EMAIL_VERIFY', 'PASSWORD_RESET', name='auth_token_kind'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('guilds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'ARCHIVED', name='guild_status'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guilds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guilds_code'), ['code'], unique=True)

    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('player_class', sa.Enum('DUELISTA', 'COLECCIONISTA', 'ESTRATEGA', 'MENTOR', 'TRADER', 'EXPLORADOR', name='player_class'), nullable=False),
    sa.Column('elite_id_code', sa.String(length=20), nullable=False),
    sa.Column('elite_id_number', sa.Integer(), nullable=False),
    sa.Column('prestige', sa.Integer(), nullable=False),
    sa.Column('favorite_game_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['favorite_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elite_id_number'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_profiles_alias'), ['alias'], unique=True)
        batch_op.create_index(batch_op.f('ix_player_profiles_elite_id_code'), ['elite_id_code'], unique=True)

    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=120), nullable=True),
    sa.Column('is_seasonal', sa.Boolean(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_guild_id'), ['guild_id'], unique=False)

    op.create_table('admin_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_kind', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_action_log_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_action_log_guild_id'), ['guild_id'], unique=False)

    op.create_table('guild_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='join_request_status'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'guild_id', 'status', name='uq_join_req_user_guild_status')
    )
    with op.batch_alter_table('guild_join_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_join_requests_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_join_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_join_requests_user_id'), ['user_id'], unique=False)

    op.create_table('guild_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'ORGANIZER', 'JUDGE', 'GUILD_ADMIN', name='guild_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'guild_id', name='uq_guild_membership')
    )
    with op.batch_alter_table('guild_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_memberships_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guild_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_player_id'), ['player_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('price_clp', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('access', sa.Enum('NORMAL', 'ELITE_ACCESS', 'ELITE_PRO', name='product_access'), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('per_player_limit', sa.Integer(), nullable=True),
    sa.Column('is_preorder', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_guild_id'), ['guild_id'], unique=False)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='season_status'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_season_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['previous_season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'number', name='uq_season_guild_number')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_guild_id'), ['guild_id'], unique=False)

    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_guild_id'), ['guild_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('CASUAL', 'COMPETITIVE', 'ELITE_CHALLENGE', 'TRADE_DAY', 'WEEKLY_LEAGUE', 'MONTHLY_LEAGUE', 'FINAL_ELITE', 'BEGINNER_EVENT', 'PREORDER_EVENT', name='event_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'FINISHED', 'CANCELLED', name='event_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('price_clp', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('rules', sa.String(length=2000), nullable=True),
    sa.Column('prizes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_season_id'), ['season_id'], unique=False)

    op.create_table('hall_of_fame_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hall_of_fame_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hall_of_fame_entries_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hall_of_fame_entries_season_id'), ['season_id'], unique=False)

    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('exp_reward', sa.Integer(), nullable=False),
    sa.Column('is_weekly', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missions_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_missions_season_id'), ['season_id'], unique=False)

    op.create_table('player_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['granted_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'achievement_id', 'season_id', name='uq_player_ach_season')
    )
    with op.batch_alter_table('player_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_achievements_achievement_id'), ['achievement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_achievements_player_id'), ['player_id'], unique=False)

    op.create_table('player_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'title_id', 'season_id', name='uq_player_title_season')
    )
    with op.batch_alter_table('player_titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_titles_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_titles_title_id'), ['title_id'], unique=False)

    op.create_table('prestige_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prestige_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prestige_transactions_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestige_transactions_season_id'), ['season_id'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PAID', 'EXPIRED', 'CANCELLED', name='reservation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_product_id'), ['product_id'], unique=False)

    op.create_table('season_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('final_level', sa.Integer(), nullable=False),
    sa.Column('final_exp_total', sa.Integer(), nullable=False),
    sa.Column('max_rank', sa.Enum('INICIADO', 'APRENDIZ', 'DUELISTA', 'RETADOR', 'ELITE', 'MAESTRO', 'CAMPEON', name='rank_name'), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('prestige_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'player_id', name='uq_season_history_unique')
    )
    with op.batch_alter_table('season_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_history_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_history_season_id'), ['season_id'], unique=False)

    op.create_table('season_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('starting_level', sa.Integer(), nullable=False),
    sa.Column('was_promoted_start', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp_in_level', sa.Integer(), nullable=False),
    sa.Column('exp_total', sa.Integer(), nullable=False),
    sa.Column('max_rank', sa.Enum('INICIADO', 'APRENDIZ', 'DUELISTA', 'RETADOR', 'ELITE', 'MAESTRO', 'CAMPEON', name='rank_name'), nullable=False),
    sa.Column('current_rank', sa.Enum('INICIADO', 'APRENDIZ', 'DUELISTA', 'RETADOR', 'ELITE', 'MAESTRO', 'CAMPEON', name='rank_name'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'player_id', name='uq_season_progress_unique')
    )
    with op.batch_alter_table('season_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_progress_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_progress_season_id'), ['season_id'], unique=False)

    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('attendance_status', sa.Enum('PENDING', 'ATTENDED', 'NO_SHOW', name='attendance_status'), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('rounds_won', sa.Integer(), nullable=False),
    sa.Column('rounds_lost', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id', name='uq_event_reg_unique')
    )
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_registrations_player_id'), ['player_id'], unique=False)

    op.create_table('exp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('related_event_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['related_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exp_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exp_transactions_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exp_transactions_season_id'), ['season_id'], unique=False)

    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['player_a_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['player_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_results_event_id'), ['event_id'], unique=False)

    op.create_table('player_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'mission_id', name='uq_player_mission')
    )
    with op.batch_alter_table('player_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_missions_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_missions_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_missions_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_missions_mission_id'))

    op.drop_table('player_missions')
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_results_event_id'))

    op.drop_table('match_results')
    with op.batch_alter_table('exp_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exp_transactions_season_id'))
        batch_op.drop_index(batch_op.f('ix_exp_transactions_player_id'))

    op.drop_table('exp_transactions')
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_registrations_player_id'))
        batch_op.drop_index(batch_op.f('ix_event_registrations_event_id'))

    op.drop_table('event_registrations')
    with op.batch_alter_table('season_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_progress_season_id'))
        batch_op.drop_index(batch_op.f('ix_season_progress_player_id'))

    op.drop_table('season_progress')
    with op.batch_alter_table('season_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_history_season_id'))
        batch_op.drop_index(batch_op.f('ix_season_history_player_id'))

    op.drop_table('season_history')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_product_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_player_id'))

    op.drop_table('reservations')
    with op.batch_alter_table('prestige_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestige_transactions_season_id'))
        batch_op.drop_index(batch_op.f('ix_prestige_transactions_player_id'))

    op.drop_table('prestige_transactions')
    with op.batch_alter_table('player_titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_titles_title_id'))
        batch_op.drop_index(batch_op.f('ix_player_titles_player_id'))

    op.drop_table('player_titles')
    with op.batch_alter_table('player_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_achievements_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_achievements_achievement_id'))

    op.drop_table('player_achievements')
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missions_season_id'))
        batch_op.drop_index(batch_op.f('ix_missions_guild_id'))

    op.drop_table('missions')
    with op.batch_alter_table('hall_of_fame_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hall_of_fame_entries_season_id'))
        batch_op.drop_index(batch_op.f('ix_hall_of_fame_entries_player_id'))

    op.drop_table('hall_of_fame_entries')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_season_id'))
        batch_op.drop_index(batch_op.f('ix_events_guild_id'))
        batch_op.drop_index(batch_op.f('ix_events_game_id'))

    op.drop_table('events')
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_guild_id'))

    op.drop_table('titles')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_guild_id'))

    op.drop_table('seasons')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_guild_id'))
        batch_op.drop_index(batch_op.f('ix_products_game_id'))

    op.drop_table('products')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_player_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_guild_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('guild_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_guild_memberships_guild_id'))

    op.drop_table('guild_memberships')
    with op.batch_alter_table('guild_join_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_join_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_guild_join_requests_status'))
        batch_op.drop_index(batch_op.f('ix_guild_join_requests_guild_id'))

    op.drop_table('guild_join_requests')
    with op.batch_alter_table('admin_action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_action_log_guild_id'))
        batch_op.drop_index(batch_op.f('ix_admin_action_log_admin_id'))

    op.drop_table('admin_action_log')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_guild_id'))

    op.drop_table('achievements')
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_profiles_elite_id_code'))
        batch_op.drop_index(batch_op.f('ix_player_profiles_alias'))

    op.drop_table('player_profiles')
    with op.batch_alter_table('guilds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guilds_code'))

    op.drop_table('guilds')
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_kind'))

    op.drop_table('auth_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_code'))

    op.drop_table('games')
    # ### end Alembic commands ###
